## Test Endpoint

GET http://localhost:3000/healthcheck

### Get User Information

GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjIyMTFjMjVmMmE2YWJmZmQ0YzYwZWQiLCJuYW1lIjoiRmFiaW8tdGVzdC0yIiwiZW1haWwiOiJkY2ZhYmlvLXRlc3QtMkBnbWFpbC5jb20iLCJpYXQiOjE3MTM1MDg4MDIsImV4cCI6MTcxMzUwOTcwMn0.Q3NsS4sGeLjiPbKCX-HtS5dnnY71Lc0Sp2wtfVqv9Zs

### Login

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "dcfabio-test@gmail.com",
    "password": "123"
}

### Sign Up

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "name": "Fabio-test",
    "email": "dcfabio-test@gmail.com",
    "password": "123"
}

### Test Endpoints with Authorization DELETE

DELETE http://localhost:3000/auth/662211c25f2a6abffd4c60ed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjIyMGUyZjczZmU4MTM5YWY2ZmI0YzYiLCJuYW1lIjoiRmFiaW8tVGVzdC0yIiwiZW1haWwiOiJkY2ZhYmlvVGVzdC0zQGdtYWlsLmNvbSIsImlhdCI6MTcxMzUwODEzNSwiZXhwIjoxNzEzNTA5MDM1fQ.rLzBhsRQZ-B_noS9WPL9jQrYokuh4L3seh_8gqCXpbk

### Test Endpoints with Authorization PUT

PUT http://localhost:3000/auth/662211c25f2a6abffd4c60ed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjIyMTFjMjVmMmE2YWJmZmQ0YzYwZWQiLCJuYW1lIjoiRmFiaW8tdGVzdC0yIiwiZW1haWwiOiJkY2ZhYmlvLXRlc3QtMkBnbWFpbC5jb20iLCJpYXQiOjE3MTM1MDg4MDIsImV4cCI6MTcxMzUwOTcwMn0.Q3NsS4sGeLjiPbKCX-HtS5dnnY71Lc0Sp2wtfVqv9Zs

{
    "email": "dcfabio-test-2@gmail.com",
    "password": "123"
}
