## Test Endpoint

GET http://localhost:4000/healthcheck

### Get User Information

GET http://localhost:4000/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTMyODM5NzAsInVzZXJfaWQiOiI2NjE3ZWQ2ZTc5YmI1ZWRjZjVkYTYwODMifQ.LFr2G7aBfXyGdRRLLO4DIo9gxBoDSGvU2-lyldc0-Lo

### Login

POST http://localhost:4000/api/v1/auth/login
Content-Type: application/json

{
    "email": "dcfabioTest@gmail.com",
    "password": "123"
}

### Sign Up

POST http://localhost:4000/api/v1/auth/signup
Content-Type: application/json

{
    "name": "Fabio Test",
    "email": "dcfabioTest@gmail.com",
    "password": "123"
}


### Test Endpoints with Authorization

DELETE http://localhost:4000/api/v1/auth/661d5597bf28d10d1dab1209
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTMyODUwOTgsInVzZXJfaWQiOiI2NjFkNTU5N2JmMjhkMTBkMWRhYjEyMDkifQ.n11ILRIDUdHE8kNvIwstqELThEsDbEjhAnuye_bYves