## Test Endpoint

GET http://localhost:4000/healthcheck

### Get User Information

GET http://localhost:4000/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTMyODM5NzAsInVzZXJfaWQiOiI2NjE3ZWQ2ZTc5YmI1ZWRjZjVkYTYwODMifQ.LFr2G7aBfXyGdRRLLO4DIo9gxBoDSGvU2-lyldc0-Lo

### Login

POST http://localhost:4000/api/v1/auth/login
Content-Type: application/json

{
    "email": "dcfabioTest@gmail.com",
    "password": "123"
}

### Sign Up

POST http://localhost:4000/api/v1/auth/signup
Content-Type: application/json

{
    "name": "Fabio Test",
    "email": "dcfabioTest@gmail.com",
    "password": "123"
}


### Test Endpoints with Authorization DELETE

DELETE http://localhost:4000/api/v1/auth/661d57d5e352179d2009c4c4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTMyODU0NjEsInVzZXJfaWQiOiI2NjFkNTdkNWUzNTIxNzlkMjAwOWM0YzQifQ.GvH1tXxaUBrPWyrCUpaRg0KZVhaGfJZjM6_jVUMXl24

### Test Endpoints with Authorization PUT

PUT http://localhost:4000/api/v1/auth/661d57d5e352179d2009c4c4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTMyODU0NjEsInVzZXJfaWQiOiI2NjFkNTdkNWUzNTIxNzlkMjAwOWM0YzQifQ.GvH1tXxaUBrPWyrCUpaRg0KZVhaGfJZjM6_jVUMXl24

{
    "name": "Fabio Test 2",
    "email": "dcfabioTest@gmail.com",
    "password": "123"
}
